spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - GET
              - OPTIONS
            allowedHeaders:
              - "*"
      routes:
        - id: posts-route
          uri: http://157.230.41.132:8080
          predicates:
            - Path=/backend/**
          filters:
            - StripPrefix=1
            - SetResponseHeader=Access-Control-Allow-Origin, http://157.230.41.132