spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*" # Replace with the actual origin you want to allow
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: backend
          uri: http://157.230.41.132:8080
          predicates:
            - Path=/backend/**
